/**
 * Writes every character sprite sheet in the game, from code.
 *
 *   node tools/build-sprites.mjs
 *
 * The drawing itself lives in tools/knight.mjs so the preview tooling can
 * import it without triggering a build. Nothing binary is committed: CI runs
 * this and the output is byte-identical, because the encoder is deterministic.
 */
import fs from 'node:fs';
import path from 'node:path';
import { Px } from './pixel.mjs';
import { HOUSES, ANIMS, knightFrame, W, H } from './knight.mjs';

const OUT = path.resolve('public/sprites');

function sheet(house) {
  const names = Object.keys(ANIMS);
  const cols = Math.max(...names.map((n) => ANIMS[n].length));
  const out = new Px(W * cols, H * names.length);
  names.forEach((name, row) => {
    ANIMS[name].forEach((pose, col) => {
      out.blit(knightFrame(house, pose), col * W, row * H);
    });
  });
  return { px: out, rows: names, cols };
}

fs.mkdirSync(OUT, { recursive: true });
console.log('building sprites');

const manifest = { frame: { w: W, h: H }, anims: {}, houses: [] };
Object.keys(ANIMS).forEach((name, row) => {
  manifest.anims[name] = { row, frames: ANIMS[name].length, fps: name === 'idle' ? 6 : 12 };
});

let total = 0;
for (const [name, house] of Object.entries(HOUSES)) {
  const { px, rows, cols } = sheet(house);
  const png = px.png();
  fs.writeFileSync(path.join(OUT, `knight-${name}.png`), png);
  total += png.length;
  manifest.houses.push(name);
  console.log(
    `  knight-${name}.png`.padEnd(28),
    String(png.length).padStart(6),
    'bytes',
    `(${px.w}x${px.h}, ${rows.length} anims x ${cols} frames)`
  );
}

fs.writeFileSync(path.join(OUT, 'sprites.json'), JSON.stringify(manifest, null, 2) + '\n');

// A typed manifest for the UI, so a frame count can never drift from the sheet.
const ts =
  `/* Generated by tools/build-sprites.mjs. Do not edit: run \`npm run build:sprites\`. */\n\n` +
  `export const FRAME = { w: ${W}, h: ${H} } as const;\n\n` +
  `export const HOUSES = [${manifest.houses.map((h) => `'${h}'`).join(', ')}] as const;\n` +
  `export type House = (typeof HOUSES)[number];\n\n` +
  `export const ANIMS = {\n` +
  Object.entries(manifest.anims)
    .map(([k, v]) => `  ${k}: { row: ${v.row}, frames: ${v.frames}, fps: ${v.fps} },`)
    .join('\n') +
  `\n} as const;\n` +
  `export type AnimName = keyof typeof ANIMS;\n\n` +
  `/** Widest row on the sheet, in frames. */\n` +
  `export const COLUMNS = ${Math.max(...Object.values(manifest.anims).map((a) => a.frames))};\n`;
fs.writeFileSync(path.resolve('src/ui/sprites.generated.ts'), ts);
console.log(`  ---\n  ${Object.keys(HOUSES).length} houses, ${(total / 1024).toFixed(1)} KB total`);
