/**
 * Bundles the UI fonts into the app.
 *
 *   node tools/build-fonts.mjs
 *
 * The app previously pulled Silkscreen and Outfit from fonts.googleapis.com at
 * runtime. In a packaged Android app that is wrong twice over: the display face
 * silently falls back to a system serif on a cold or offline first launch, and
 * every launch hands a user's IP to a third party, which is a consent question
 * in the EU. So the woff2 files ship inside the APK.
 *
 * Fetches the same css2 endpoint a browser would, keeps the latin subset of
 * each face, and writes src/ui/theme/fonts.css with local @font-face rules.
 */
import fs from 'node:fs';
import path from 'node:path';

const OUT_DIR = path.resolve('public/fonts');
const CSS_OUT = path.resolve('src/ui/theme/fonts.css');

// A modern UA, or the API serves truetype for ancient browsers instead of woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  { family: 'Silkscreen', weights: [400, 700] },
  { family: 'Outfit', weights: [400, 600, 700] },
];

/** The latin block is the one that covers U+0041 (A); the rest are subsets we never render. */
function isLatin(range) {
  return /U\+0000-00FF/.test(range) || /U\+0020/.test(range);
}

function parseFaces(css) {
  return [...css.matchAll(/@font-face\s*{([^}]*)}/g)].map(([, body]) => {
    const get = (k) => (body.match(new RegExp(`${k}:\\s*([^;]+);`)) || [])[1]?.trim();
    return {
      family: (get('font-family') || '').replace(/['"]/g, ''),
      weight: get('font-weight') || '400',
      style: get('font-style') || 'normal',
      range: get('unicode-range') || '',
      url: (get('src') || '').match(/url\((https:[^)]+)\)/)?.[1] || '',
    };
  });
}

console.log('building fonts');
fs.mkdirSync(OUT_DIR, { recursive: true });

const rules = [];
let total = 0;

for (const { family, weights } of FAMILIES) {
  const spec = `${family.replace(/ /g, '+')}:wght@${weights.join(';')}`;
  const res = await fetch(`https://fonts.googleapis.com/css2?family=${spec}&display=swap`, {
    headers: { 'User-Agent': UA },
  });
  if (!res.ok) throw new Error(`${family}: css2 returned ${res.status}`);
  const faces = parseFaces(await res.text()).filter((f) => f.url && isLatin(f.range));

  // A variable family serves ONE file for every weight. Writing it once per
  // weight would ship the same 32 KB three times, so group by url first.
  const byUrl = new Map();
  for (const weight of weights) {
    const face = faces.find((f) => f.weight === String(weight) || f.weight.split(' ').includes(String(weight)));
    if (!face) throw new Error(`${family} ${weight}: no latin face in the css2 response`);
    if (!byUrl.has(face.url)) byUrl.set(face.url, []);
    byUrl.get(face.url).push(weight);
  }

  for (const [url, ws] of byUrl) {
    const variable = ws.length > 1;
    const file = `${family.toLowerCase()}-${variable ? 'var' : ws[0]}.woff2`;
    const bytes = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    fs.writeFileSync(path.join(OUT_DIR, file), bytes);
    total += bytes.length;
    console.log(`  ${file.padEnd(26)} ${String(bytes.length).padStart(6)} bytes  (weight ${ws.join(', ')})`);
    rules.push(
      `@font-face {\n` +
      `  font-family: '${family}';\n` +
      `  font-style: normal;\n` +
      `  font-weight: ${variable ? `${Math.min(...ws)} ${Math.max(...ws)}` : ws[0]};\n` +
      `  font-display: swap;\n` +
      `  src: url('/fonts/${file}') format('woff2');\n` +
      `}`
    );
  }
}

fs.writeFileSync(
  CSS_OUT,
  '/* Generated by tools/build-fonts.mjs. Do not edit: run `npm run build:fonts`. */\n' +
    rules.join('\n\n') +
    '\n'
);
console.log(`  ---\n  ${rules.length} faces, ${(total / 1024).toFixed(1)} KB -> src/ui/theme/fonts.css`);
